FROM floydhub/dl-base:v1-py3
MAINTAINER Floyd Labs "support@floydhub.com"

RUN pip --no-cache-dir install --upgrade http://download.pytorch.org/whl/cu80/torch-0.1.11.post5-cp35-cp35m-linux_x86_64.whl

RUN pip --no-cache-dir install --upgrade torchvision