FROM floydhub/dl-base:1.0.0-py2
MAINTAINER Floyd Labs "support@floydhub.com"

RUN pip --no-cache-dir install --upgrade http://download.pytorch.org/whl/cu80/torch-0.1.11.post5-cp27-none-linux_x86_64.whl

RUN pip --no-cache-dir install --upgrade torchvision