FROM floydhub/tensorflow:2.0-py3_aws.46
MAINTAINER Floyd Labs "support@floydhub.com"

RUN pip --no-cache-dir install --upgrade \
        http://download.pytorch.org/whl/cpu/torch-1.2.0-cp36-cp36m-manylinux1_x86_64.whl \
        # Torchvision is now built with CUDA https://github.com/pytorch/vision/issues/946 
        https://download.pytorch.org/whl/cpu/torchvision-0.4.0-cp36-cp36m-manylinux1_x86_64.whl \
        torchtext==0.4.0 \
        tensorboardX==1.8 \
        fastai \
        transformers \
    && rm -rf /tmp/* \
    && rm -rf /root/.cache