FROM floydhub/dl-python:latest-py2
MAINTAINER Floyd Labs "support@floydhub.com"

RUN apt-get update && apt-get install -y \
        python-opencv \
        libavcodec-dev \
		libavformat-dev \
		libav-tools \
		libdc1394-22-dev \
        libgdal-dev \
        libgtk2.0-dev \
        libjasper-dev \
        libopencore-amrnb-dev \
        libopencore-amrwb-dev \
        libopencv-dev \
        libopenexr-dev \
        libswscale-dev \
		libtbb2 \
		libtbb-dev \
		libtheora-dev \
        libv4l-dev \
        libvorbis-dev \
        libvtk6-dev \
        libx264-dev \
        libxine2-dev \
		libxvidcore-dev \
        qt5-default \
        && \
	apt-get clean && \
	apt-get autoremove && \
	rm -rf /var/lib/apt/lists/*

RUN cd ~/ &&\
    git clone https://github.com/Itseez/opencv.git &&\
    git clone https://github.com/Itseez/opencv_contrib.git &&\
    cd opencv && \
    mkdir build && \
    cd build && \
    cmake  -DWITH_QT=ON -DWITH_OPENGL=ON -DFORCE_VTK=ON -DWITH_TBB=ON -DWITH_GDAL=ON -DWITH_XINE=ON -DBUILD_EXAMPLES=ON .. && \
    make -j"$(nproc)" && \
    make install && \
    ldconfig && \
 # Remove the opencv folders to reduce image size
    rm -rf ~/opencv* && \
    echo 'ln /dev/null /dev/raw1394' >> ~/.bashrc
