FROM floydhub/dl-base:latest-py3
MAINTAINER Floyd Labs "support@floydhub.com"

RUN pip --no-cache-dir install --upgrade https://s3.amazonaws.com/pytorch/whl/cu80/torch-0.1.9.post2-cp35-cp35m-linux_x86_64.whl 

RUN pip --no-cache-dir install --upgrade torchvision