FROM floydhub/dl-opencv:latest-py2
MAINTAINER Floyd Labs "support@floydhub.com"

RUN pip --no-cache-dir --upgrade install https://s3.amazonaws.com/pytorch/whl/cu80/torch-0.1.9.post2-cp27-none-linux_x86_64.whl 

RUN pip --no-cache-dir --upgrade install torchvision