FROM floydhub/tensorflow:1.9.0-py3_aws.35
MAINTAINER Floyd Labs "support@floydhub.com"

RUN pip --no-cache-dir install --upgrade \
        torchvision==0.2.1 \
        torchtext \
        tensorboardX==1.2 \
        pip \
        fastai \
    && rm -rf /tmp/* \
    && rm -rf /root/.cache

RUN pip --no-cache-dir install --upgrade \
        torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html \
    && rm -rf /tmp/* \
    && rm -rf /root/.cache
