FROM floydhub/dl-opencv:latest-gpu-py3
MAINTAINER Floyd Labs "support@floydhub.com"

ARG CHAINER_VERSION=v1.21.0

RUN pip install --no-cache-dir --upgrade chainer==${CHAINER_VERSION}

# TODO: Move this to floydhub/dl-python
RUN chmod +x /run_jupyter.sh

# TODO: Move this to dl-python
RUN mv /root/.jupyter/jupyter_notebook_config_py3.py /root/.jupyter/jupyter_notebook_config.py 