FROM floydhub/dl-opencv:latest-gpu-py3
MAINTAINER Floyd Labs "support@floydhub.com"

RUN pip install --upgrade tensorflow-gpu==1.0.0

ARG KERAS_VERSION=1.2.2
RUN pip --no-cache-dir install git+git://github.com/fchollet/keras.git@${KERAS_VERSION}