FROM floydhub/dl-opencv:latest-py2
MAINTAINER Floyd Labs "support@floydhub.com"

RUN pip install --upgrade tensorflow==1.0.0

ARG KERAS_VERSION=1.2.2
RUN pip --no-cache-dir install git+git://github.com/fchollet/keras.git@${KERAS_VERSION}

# TODO: Move this to floydhub/dl-python
RUN chmod +x /run_jupyter.sh

# TODO: Move this to dl-python
RUN mv /root/.jupyter/jupyter_notebook_config_py2.py /root/.jupyter/jupyter_notebook_config.py 
