FROM floydhub/dl-base:latest-gpu-py2
MAINTAINER Floyd Labs "support@floydhub.com"

ARG KERAS_VERSION=2.0.3

RUN pip install --upgrade tensorflow-gpu==1.0.0

RUN pip --no-cache-dir install git+git://github.com/fchollet/keras.git@${KERAS_VERSION}