FROM floydhub/dl-base:v1-py3
MAINTAINER Floyd Labs "support@floydhub.com"

ARG TENSORFLOW_VERSION=1.1.0
ARG KERAS_VERSION=2.0.4

ARG TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-${TENSORFLOW_VERSION}-cp35-cp35m-linux_x86_64.whl

RUN pip --no-cache-dir install --upgrade ${TF_BINARY_URL}

# Install Keras
RUN pip --no-cache-dir install git+git://github.com/fchollet/keras.git@${KERAS_VERSION}
