FROM floydhub/tensorflow:1.9.0-gpu.cuda9cudnn7-py2_aws.33
MAINTAINER Floyd Labs "support@floydhub.com"

RUN pip --no-cache-dir install --upgrade http://download.pytorch.org/whl/cu91/torch-0.4.1-cp27-cp27mu-linux_x86_64.whl \
    torchvision==0.2.1


RUN pip --no-cache-dir install --upgrade \
        torchtext \
{-% if _tensorboardx_version is defined %}
        tensorboardX==1.2 \
{-% endif %}
        git+https://github.com/fastai/fastai.git \
    && rm -rf /tmp/* \
    && rm -rf /root/.cache