FROM floydhub/dl-base:2.1.0-gpu-py2.22
MAINTAINER Floyd Labs "support@floydhub.com"

RUN pip --no-cache-dir install --upgrade http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp27-cp27mu-linux_x86_64.whl \
    tensorboardX \
    torchvision==0.2.0
