FROM floydhub/dl-base-gpu:latest
MAINTAINER Floyd Labs "support@floydhub.com"

RUN pip --no-cache-dir install \
        Cython \
        h5py \
        ipykernel \
        jupyter \
        matplotlib \
        numpy \
        pandas \
        path.py \
        scipy \
        six \
        skimage \
        sklearn \
        sympy \
        Pillow \
        zmq \
        && \
    python -m ipykernel.kernelspec