FROM floydhub/dl-opencv:latest-py3
MAINTAINER Floyd Labs "support@floydhub.com"

RUN git clone --recursive https://github.com/dmlc/mxnet/ && cd mxnet && \
    cp config.mk . && \
    echo "USE_BLAS=openblas" >>config.mk && \
    make -j$(nproc)

ENV PYTHONPATH /mxnet/python