FROM floydhub/dl-opencv:latest-gpu-py2
MAINTAINER Floyd Labs "support@floydhub.com"

COPY config.mk /

RUN git clone --recursive https://github.com/dmlc/mxnet && cd mxnet && \
  sed -i 's/USE_BLAS = atlas/USE_BLAS = openblas/g' config.mk && \
  sed -i 's/USE_CUDA = 0/USE_CUDA = 1/g' config.mk && \
  sed -i 's/USE_CUDA_PATH = NONE/USE_CUDA_PATH = \/usr\/local\/cuda/g' config.mk && \
  sed -i 's/USE_CUDNN = 0/USE_CUDNN = 1/g' config.mk && \
  make -j"$(nproc)"

ENV PYTHONPATH /mxnet/python