FROM floydhub/dl-opencv:latest-py2
MAINTAINER Floyd Labs "support@floydhub.com"

COPY config.mk /

RUN git clone --recursive https://github.com/dmlc/mxnet/ && cd mxnet && \
    echo "USE_BLAS=openblas" >>config.mk && \
    make -j$(nproc)

ENV PYTHONPATH /mxnet/python