FROM floydhub/tensorflow:1.8.0-py3_aws.30
MAINTAINER Floyd Labs "support@floydhub.com"

RUN \
    pip --no-cache-dir install \
        mxnet==1.0.0.post4 \
        tensorboardX \
    && rm -rf /tmp/* \
    && rm -rf /root/.cache