FROM floydhub/dl-base:v1-gpu-py2
MAINTAINER Floyd Labs "support@floydhub.com"

ARG TENSORFLOW_VERSION=1.0.1
ARG TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-${TENSORFLOW_VERSION}-cp27-none-linux_x86_64.whl
ARG KERAS_VERSION=2.0.4

RUN pip --no-cache-dir install --upgrade ${TF_BINARY_URL}

# Install Keras
RUN pip --no-cache-dir install git+git://github.com/fchollet/keras.git@${KERAS_VERSION}